name: pyagnps
channels:
  - conda-forge
  - plotly
  - defaults
dependencies:
  - requests
  - pandas
  - rasterstats
  - ipykernel
  - geopandas
  - rioxarray
  - pygeoogc
  - plotly_express
  - nbformat
  - altair
  - py3dep
  - matplotlib