name: pyagnps
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.9
  - tqdm>=4.65.0
  - shapely>=2.0.1
  - rioxarray>=0.14.1
  - requests>=2.29.0
  - rasterio>=1.3.6
  - py3dep>=0.14.0
  - pandas>=2.0.1
  - numpy>=1.24.3
  - networkx>=3.1
  - lxml>=4.9.2
  - geopandas>=0.12.2
  - psycopg2-binary>=2.9.6
  - sqlalchemy>=2.0.12
  - matplotlib>=3.7.1
  - rasterstats>=0.18.0
  - folium>=0.14.0
  - mapclassify>=2.5.0
  - pyarrow>=12.0.1
  - pyogrio>=0.6.0
  - fastparquet>=2023.7.0
  - holoviews>=1.17.1
  - hvplot>=0.8.4
  - selenium>=4.10.0
  - pynldas2>=0.15.1
  - pydaymet>=0.15.1
  - timezonefinder>=6.2.0
  - jupyter_bokeh>=3.0.7
  - pooch>=1.7.0
  - nc-time-axis>=1.4.1
  - dask>=2023.9.3
  - xarray>=2023.9.0
  - gdal>=3.6.2
  - nbformat>=5.8.0
  - ipykernel>=6.22.0