# COLLECTION OF AIMS SPECIFIC SCRIPTS AND METHODS
# REFACTORED TEMPLATE
import warnings
warnings.filterwarnings("ignore", category=UserWarning)
warnings.filterwarnings("ignore", category=RuntimeWarning)

import json
import time
import copy
import itertools
from pathlib import Path
from datetime import datetime
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any, Tuple

import pandas as pd
import geopandas as gpd
from sqlalchemy import create_engine, text as sql_text, URL
from sqlalchemy.engine import Engine
from pyagnps import annagnps, utils, constants, climate
from pyagnps.utils import (
    relative_input_file_path, write_csv_control_file_from_dict,
    convert_dict_to_df, get_relative_path
)
from tqdm import tqdm

# =============================================================================
# 1. CONFIGURATION DATACLASS
# Replaces the __init__ **kwargs with an explicit configuration object
# =============================================================================
@dataclass
class AIMSWatershedConfig:
    """Explicit configuration for an AIMS Watershed simulation."""
    # Outlet identification
    thuc_id: Optional[int] = None
    reach_id: Optional[int] = None
    outlet_x: Optional[float] = None  # In EPSG 4326
    outlet_y: Optional[float] = None

    # Date range
    start_date: Optional[str] = None
    end_date: Optional[str] = None

    # Metadata
    watershed_name: str = "AIMS Watershed"
    watershed_description: str = "Watershed generated by pyAGNPS and AIMS"
    watershed_location: str = "A Watershed in continental United States"

    # Climate settings
    climate_method: str = "nldas2_database"
    keep_potential_et: bool = True
    date_mode: str = "local"
    climate_table: str = "climate_nldas2"

    # CMIP paths
    path_to_cmip_dir: Optional[Path] = None
    path_to_cmip_station_points_id: Optional[Path] = None

    # Static file paths (optional, will be downloaded if None)
    path_to_nldas2_centroids: Optional[Path] = None
    path_to_scs_storm_types: Optional[Path] = None
    path_to_precip_zones: Optional[Path] = None

    # Output settings
    output_folder: Path = field(default_factory=lambda: Path(f"/tmp/watershed_run_{get_now_string()}"))
    export_gis: bool = True
    overwrite: bool = True
    MAXITER_CLIMATE_QUERY: int = 10
    selected_reaches_for_output: List[str] = field(default_factory=lambda: ['OUTLET'])

    # AnnAGNPS Dictionaries
    global_factors_flags_dict: Dict[str, Any] = field(default_factory=lambda: constants.DEFAULT_GLOBAL_FACTORS_FLAGS)
    output_options_global_dict: Dict[str, Any] = field(default_factory=lambda: constants.DEFAULT_OUTPUT_OPTIONS_GLOBAL)
    output_options_aa_dict: Dict[str, Any] = field(default_factory=lambda: constants.DEFAULT_OUTPUT_OPTIONS_AA)
    output_options_tbl_dict: Dict[str, Any] = field(default_factory=lambda: constants.DEFAULT_OUTPUT_OPTIONS_TBL)
    annagnps_id_dict: Dict[str, Any] = field(default_factory=lambda: constants.DEFAULT_ANNAGNPS_ID)
    simulation_period_data_dict: Dict[str, Any] = field(default_factory=lambda: constants.DEFAULT_SIM_PERIOD_DATA)

# =============================================================================
# 2. STATIC ASSET LOADER
# Helper class to load or download static GIS files
# =============================================================================
class StaticAssetLoader:
    """Handles loading and downloading of static GIS assets."""

    def load_nldas2_centroids(self, path_to_nldas2_centroids: Optional[Path]) -> gpd.GeoDataFrame:
        # ... implementation from original file's load_nldas2_centroids ...
        # (This method contains the logic to download if not exists)
        print("Loading NLDAS-2 Centroids...")
        url_nldas2_centroids = "https://amazon.ncche.olemiss.edu:8443/Luc/pyagnps/-/raw/main/inputs/climate/NLDAS2_GRID_CENTROIDS_epsg4326.gpkg"
        if path_to_nldas2_centroids is None:
            path_to_nldas2_centroids = Path().cwd() / "gis_temp" / "NLDAS2_GRID_CENTROIDS_epsg4326.gpkg"
        
        if not(path_to_nldas2_centroids.exists()):
            utils.download_simple_file(url_nldas2_centroids, out_dir=path_to_nldas2_centroids.parent)            
        return gpd.read_file(path_to_nldas2_centroids)

    def load_scs_storm_types(self, path_to_scs_storm_types: Optional[Path]) -> gpd.GeoDataFrame:
        # ... implementation from original file's load_scs_storm_types ...
        print("Loading SCS Storm Types...")
        url_scs_storm_types = "https://amazon.ncche.olemiss.edu:8443/Luc/rusle2-climate-shapefile/-/raw/main/data/scs_storm_types.gpkg"
        if path_to_scs_storm_types is None:
            path_to_scs_storm_types = Path().cwd() / "gis_temp" / "scs_storm_types.gpkg"
            
        if not(path_to_scs_storm_types.exists()):
            utils.download_simple_file(url_scs_storm_types, out_dir=path_to_scs_storm_types.parent)            
        return gpd.read_file(path_to_scs_storm_types).to_crs("epsg:4326")

    def load_precip_zones(self, path_to_precip_zones: Optional[Path]) -> gpd.GeoDataFrame:
        # ... implementation from original file's load_precip_zones ...
        print("Loading Precipitation Zones...")
        url_precip_zones = "https://amazon.ncche.olemiss.edu:8443/Luc/rusle2-climate-shapefile/-/raw/main/outputs/precip_zones_RUSLE2_cleaned_manually_extrapolated_pchip_linear_US_units.gpkg"
        if path_to_precip_zones is None:
            path_to_precip_zones = Path().cwd() / "gis_temp" / "precip_zones_RUSLE2_cleaned_manually_extrapolated_pchip_linear_US_units.gpkg"

        if not(path_to_precip_zones.exists()):
            utils.download_simple_file(url_precip_zones, out_dir=path_to_precip_zones.parent)            
        return gpd.read_file(path_to_precip_zones)

# =============================================================================
# 3. DATA REPOSITORY CLASS
# Handles all database query logic
# =============================================================================
class WatershedRepository:
    """Responsible for all database interactions."""
    def __init__(self, engine: Engine):
        self.engine = engine

    def get_thuc_id_by_xy(self, x: float, y: float) -> int:
        """Returns the thuc_id for which the coordinates belong to."""
        sql = sql_text(f"SELECT thuc_near_run_id_tr({x},{y})")
        # No 'with' block needed here, as passing the engine to pandas
        # handles connection lifecycle automatically.
        thuc = pd.read_sql(sql, self.engine)
        return thuc.iloc[0].values[0]

    def get_outlet_xy_from_thuc_id_and_reach_id(self, thuc_id: int, reach_id: int = 2) -> Tuple[float, float]:
        """Returns the x and y coordinates of centroid of the reach_id in thuc_id."""
        sql = sql_text(
            f"""SELECT ST_X(ST_Centroid(ST_Collect(ST_Transform(geom, 4326)))) AS lon, 
                ST_Y(ST_Centroid(ST_Collect(ST_Transform(geom, 4326)))) AS lat 
            FROM thuc_{thuc_id}_annagnps_reach_ids
            WHERE dn = {reach_id}
            """
        )
        df = pd.read_sql(sql, self.engine)
        x, y = df["lon"].to_list()[0], df["lat"].to_list()[0]
        return x, y

    def query_cells(self, thuc_id: int, lon: float, lat: float, perform_data_checks: bool = True) -> Tuple[gpd.GeoDataFrame, pd.DataFrame, List[int]]:
        """Queries and processes cell geometry and data."""
        cells_query = f"SELECT geom, cell_id FROM thuc_cell_geo_tr({lon},{lat}, '{thuc_id}')"
        with self.engine.connect() as conn:
            cells_geometry = gpd.read_postgis(sql=sql_text(cells_query), con=conn, geom_col='geom')
        
        cells_geometry = cells_geometry.dissolve(by='cell_id').reset_index()
        cells_list = cells_geometry['cell_id'].unique().tolist()
        
        cells_string = ", ".join(map(str, cells_list))
        cells_data_section_sql = f"SELECT * FROM thuc_{thuc_id}_annagnps_cell_data_section WHERE cell_id in ({cells_string})"
        
        with self.engine.connect() as conn:
            df_cells = pd.read_sql_query(sql=sql_text(cells_data_section_sql), con=conn)
        
        # ... rest of implementation from original query_cells ...
        columns = [col for col in df_cells.columns if col not in ['soil_id_annagnps_valid']]
        df_cells = df_cells[columns]
        if perform_data_checks:
            df_cells = annagnps.check_cell_data(df_cells)
        cells_geometry = cells_geometry.merge(df_cells, on='cell_id')
        
        return cells_geometry, df_cells, cells_list

    def query_reaches(self, thuc_id: int, lon: float, lat: float) -> Tuple[gpd.GeoDataFrame, pd.DataFrame, List[int]]:
        """Queries and processes reach geometry and data."""
        reaches_query = f"SELECT geom, reach_id FROM thuc_reach_geo_tr({lon},{lat}, '{thuc_id}')"
        with self.engine.connect() as conn:
            reaches_geometry = gpd.read_postgis(sql=sql_text(reaches_query), con=conn, geom_col='geom')

        # ... rest of implementation from original query_reaches ...
        reaches_geometry = reaches_geometry.dissolve(by='reach_id').reset_index()
        reaches_list = reaches_geometry['reach_id'].unique().tolist()
        reaches_string = ", ".join(map(str, reaches_list))
        reaches_data_section_sql = f"SELECT * FROM thuc_{thuc_id}_annagnps_reach_data_section WHERE reach_id in ({reaches_string})"

        with self.engine.connect() as conn:
            df_reaches = pd.read_sql_query(sql=sql_text(reaches_data_section_sql), con=conn)

        reaches_geometry = reaches_geometry.merge(df_reaches, on='reach_id')
        df_reaches_valid = annagnps.make_df_reaches_valid(df_reaches)
        
        return reaches_geometry, df_reaches_valid, reaches_list

    def query_soil(self, soil_ids_list: List[str], perform_data_checks: bool = True) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame]:
        """Queries soil, soil layers, and raw soil data."""
        soil_ids_string = ", ".join(map(str, soil_ids_list))
        
        query_soil = f"""SELECT * FROM usa_valid_soil_data WHERE "Soil_ID" in ({soil_ids_string})"""
        query_soil_layers = f"""SELECT * FROM usa_valid_soil_layers_data WHERE "Soil_ID" in ({soil_ids_string})"""
        query_raw = f"""SELECT * FROM raw_nrcs_soil_data WHERE "mukey" in ({soil_ids_string})"""
        
        with self.engine.connect() as conn:
            df_soil_data = pd.read_sql_query(sql=sql_text(query_soil), con=conn)
            df_soil_layers_data = pd.read_sql_query(sql=sql_text(query_soil_layers), con=conn).sort_values(by=['Soil_ID','Layer_Number'])
            df_raw = pd.read_sql_query(sql=sql_text(query_raw), con=conn)
            
        # ... rest of implementation from original query_soil ...
        if perform_data_checks:
            df_soil_data = annagnps.check_soil(df_soil_data)
            df_soil_layers_data = annagnps.check_soil_layers(df_soil_layers_data)
        
        return df_soil_data, df_soil_layers_data, df_raw

    # --- Management Queries ---
    # Note: These now take dependencies (lists of IDs) as arguments
    
    def query_management_field(self, mgmt_field_ids_list: List[str]) -> pd.DataFrame:
        # ... implementation from original query_management_field ...
        mgmt_field_ids_string = ", ".join(f"'{m}'" for m in mgmt_field_ids_list)
        query_mgmt_field_data = f"""SELECT * FROM annagnps_mgmt_field WHERE "Field_ID" in ({mgmt_field_ids_string})"""
        with self.engine.connect() as conn:
            return pd.read_sql_query(sql=sql_text(query_mgmt_field_data), con=conn)

    def query_management_schedule(self, mgmt_schedule_ids_list: List[str]) -> pd.DataFrame:
        # ... implementation from original query_management_schedule ...
        mgmt_schedule_ids_string = ", ".join(f"'{m}'" for m in mgmt_schedule_ids_list)
        query_mgmt_schd_data = f"""SELECT * FROM annagnps_mgmt_schd WHERE "Mgmt_Schd_ID" in ({mgmt_schedule_ids_string})"""
        with self.engine.connect() as conn:
            return pd.read_sql_query(sql=sql_text(query_mgmt_schd_data), con=conn)

    def query_management_crop(self, mgmt_crop_ids_list: List[str]) -> pd.DataFrame:
        # ... implementation from original query_management_crop ...
        if not mgmt_crop_ids_list:
             return pd.DataFrame(columns=["Crop_ID"]) # Return empty frame with expected cols
        mgmt_crop_ids_string = ", ".join(f"'{m}'" for m in mgmt_crop_ids_list)
        query_mgmt_schd_data = f"""SELECT * FROM annagnps_crop WHERE "Crop_ID" in ({mgmt_crop_ids_string})"""
        with self.engine.connect() as conn:
            return pd.read_sql_query(sql=sql_text(query_mgmt_schd_data), con=conn)

    def query_management_crop_growth(self, mgmt_crop_ids_list: List[str]) -> pd.DataFrame:
        # ... implementation from original query_management_crop_growth ...
        if not mgmt_crop_ids_list:
             return pd.DataFrame(columns=["Crop_Growth_ID"])
        mgmt_crop_ids_string = ", ".join(f"'{m}'" for m in mgmt_crop_ids_list)
        query_mgmt_crop_growth_data = f"""SELECT * FROM annagnps_crop_growth WHERE "Crop_Growth_ID" in ({mgmt_crop_ids_string})"""
        with self.engine.connect() as conn:
            return pd.read_sql_query(sql=sql_text(query_mgmt_crop_growth_data), con=conn)
        
    def query_management_non_crop(self, mgmt_non_crop_ids_list: List[str]) -> pd.DataFrame:
        # ... implementation from original query_management_non_crop ...
        if not mgmt_non_crop_ids_list:
            return pd.DataFrame(columns=["Non-Crop_ID"])
        mgmt_non_crop_ids_string = ", ".join(f"'{m}'" for m in mgmt_non_crop_ids_list)
        query_mgmt_non_cropdata = f"""SELECT * FROM annagnps_non_crop WHERE "Non-Crop_ID" in ({mgmt_non_crop_ids_string})"""
        with self.engine.connect() as conn:
            return pd.read_sql_query(sql=sql_text(query_mgmt_non_cropdata), con=conn)
        
    def query_management_operation(self, mgmt_oper_ids_list: List[str]) -> pd.DataFrame:
        # ... implementation from original query_management_operation ...
        if not mgmt_oper_ids_list:
            return pd.DataFrame(columns=["Mgmt_Operation_ID"])
        mgmt_oper_ids_string = ", ".join(f"'{m}'" for m in mgmt_oper_ids_list)
        query_mgmt_oper_data = f"""SELECT * FROM annagnps_mgmt_oper WHERE "Mgmt_Operation_ID" in ({mgmt_oper_ids_string})"""
        with self.engine.connect() as conn:
            df_mgmt_oper = pd.read_sql_query(sql=sql_text(query_mgmt_oper_data), con=conn)
        return annagnps.format_mgmt_operation_for_output(df_mgmt_oper)

    def query_runoff_curve(self, roc_ids_list: List[str]) -> pd.DataFrame:
        # ... implementation from original query_runoff_curve ...
        if not roc_ids_list:
            return pd.DataFrame(columns=["Curve_Number_ID"])
        roc_ids_string = ", ".join(f"'{m}'" for m in roc_ids_list)
        query_roc_data = f"""SELECT * FROM annagnps_runoff_curve WHERE "Curve_Number_ID" in ({roc_ids_string})"""
        with self.engine.connect() as conn:
            return pd.read_sql_query(sql=sql_text(query_roc_data), con=conn)

    # --- Climate Query ---
    # This logic was previously inside generate_climate_daily_files
    
    def query_annagnps_climate_timeseries_db(self, station_id: str, climate_table: str, start_date: str, end_date: str, keep_potential_et: bool) -> pd.DataFrame:
        """Helper function to query the climate table for a specific station."""
        return climate.query_annagnps_climate_timeseries_db(
            station_id=station_id,
            engine=self.engine,
            climate_table=climate_table,
            start_date=start_date,
            end_date=end_date,
            keep_potential_et=keep_potential_et
        )

# =============================================================================
# 4. CLIMATE PROCESSOR CLASS
# Handles climate-related logic and data generation
# =============================================================================
class ClimateProcessor:
    """Handles logic for climate data processing."""
    def __init__(self, config: AIMSWatershedConfig, repository: WatershedRepository):
        self.config = config
        self.repository = repository
        self.cmip_pts = None
        self.cmip_clm = None

    def load_cmip5_maca_station_points(self) -> None:
        """Loads CMIP5 station points and initializes the climate object."""
        # ... implementation from original load_cmip5_maca_station_points_clim_id ...
        path_to_cmip_dir = self.config.path_to_cmip_dir
        path_to_cmip_id_file = self.config.path_to_cmip_station_points_id

        if path_to_cmip_id_file is None:
            if path_to_cmip_dir is None:
                raise ValueError("Missing path_to_cmip_dir for CMIP5 processing")
            path_to_cmip_id_file = path_to_cmip_dir / "cmip5_maca_v2_metdata_pts_clim_ids.gpkg"
        
        # This logic was in your original file
        if path_to_cmip_id_file.exists():
            self.cmip_pts = gpd.read_file(path_to_cmip_id_file)
        else:
            clm = climate.ClimateAnnAGNPSCoords(coords=None, start=self.config.start_date, end=self.config.end_date)
            clm.read_cmip5_maca_data(path_to_cmip_dir.glob("*/*.nc"))
            # ... logic to create cmip_pts from scratch ...
            # ... (from original file) ...
            self.cmip_pts = ... # the created gdf
            self.cmip_pts.to_file(path_to_cmip_id_file, driver='GPKG')
        
        # Initialize the climate object for CMIP data generation
        self.cmip_clm = climate.ClimateAnnAGNPSCoords(coords=None, start=self.config.start_date, end=self.config.end_date)
        self.cmip_clm.read_cmip5_maca_data(path_to_cmip_dir.glob("*/*.nc"))


    def identify_secondary_climate_ids(self, 
                                     cells_geometry: gpd.GeoDataFrame, 
                                     nldas2_centroids: gpd.GeoDataFrame
                                     ) -> Tuple[gpd.GeoDataFrame, gpd.GeoDataFrame]:
        """Identifies nearest climate station for each cell."""
        # ... implementation from original identify_secondary_climate_ids ...
        if 'nldas2' in self.config.climate_method:
            column_station_id_name = 'nldas2_grid_ID'
            gdf_station_points = nldas2_centroids
        elif self.config.climate_method == 'cmip5':
            if self.cmip_pts is None:
                self.load_cmip5_maca_station_points()
            column_station_id_name = 'clim_id'
            gdf_station_points = self.cmip_pts
        else:
            raise ValueError(f"Unsupported climate_method: {self.config.climate_method}")

        cells_geometry = cells_geometry.sjoin_nearest(gdf_station_points)
        cells_geometry['secondary_climate_file_id'] = cells_geometry[column_station_id_name]
        cells_geometry.drop(columns=[column_station_id_name, 'index_right'], inplace=True)
        
        secondary_climate_ids = cells_geometry.loc[:,['cell_id', 'secondary_climate_file_id']].drop_duplicates(subset='cell_id')
        secondary_climate_ids = gdf_station_points.merge(secondary_climate_ids, left_on=column_station_id_name, right_on='secondary_climate_file_id')
        secondary_climate_ids.drop(columns=[column_station_id_name], inplace=True)
        secondary_climate_ids = secondary_climate_ids.set_index('cell_id').to_crs('epsg:4326')

        return cells_geometry, secondary_climate_ids

    def generate_climate_data(self, 
                              cells_geometry: gpd.GeoDataFrame, 
                              secondary_climate_ids: gpd.GeoDataFrame
                              ) -> Tuple[Dict[str, pd.DataFrame], Dict[str, Dict]]:
        """
        Generates climate dataframes and station metadata.
        Returns (climate_dataframes, climate_station_metadata)
        """
        print("Generating Climate Data...")
        climate_dataframes = {}
        climate_station_metadata = {}

        # Unique climate stations
        climate_station_points = secondary_climate_ids.drop_duplicates(subset=['secondary_climate_file_id'])
        
        clm = None # Placeholder for climate object

        for feature in tqdm(climate_station_points.iterfeatures(), total=len(climate_station_points)):
            x, y = feature['geometry']['coordinates']
            clim_id = feature['properties']['secondary_climate_file_id']
            
            if self.config.climate_method == 'nldas2_database':
                climate_station_name = f"NLDAS-2 Grid ID {clim_id}. From AIMS Database."
                df = self.repository.query_annagnps_climate_timeseries_db(
                    station_id=clim_id,
                    climate_table=self.config.climate_table,
                    start_date=self.config.start_date,
                    end_date=self.config.end_date,
                    keep_potential_et=self.config.keep_potential_et
                )
                clm = climate.ClimateAnnAGNPSCoords(coords=(x,y), start=self.config.start_date, end=self.config.end_date) # For start/end dates

            elif self.config.climate_method == 'cmip5':
                climate_station_name = f"CMIP5 MACAv2METDATA raster ID {clim_id}"
                if self.cmip_clm is None:
                    self.load_cmip5_maca_station_points()
                
                clm = self.cmip_clm
                clm.update_coords_start_end_dates(coords=(x,y), start=self.config.start_date, end=self.config.end_date, date_mode=self.config.date_mode)
                df = clm.generate_annagnps_daily_climate_data_cmip5_maca(keep_potential_et=self.config.keep_potential_et)
            
            # ... other climate methods (nldas2_data_rods) ...
            
            else:
                raise NotImplementedError(f"Climate method {self.config.climate_method} not implemented in processor.")

            climate_dataframes[clim_id] = df
            
            climate_station_metadata[clim_id] = {
                'climate_station_name': climate_station_name,
                'beginning_climate_date': clm.start.strftime("%m/%d/%Y"),
                'ending_climate_date': clm.end.strftime("%m/%d/%Y"),
                'latitude': y,
                'longitude': x,
                'elevation': cells_geometry.loc[cells_geometry['secondary_climate_file_id'] == clim_id, 'avg_elevation'].mean()
            }
        
        # Add a "global" entry for the last processed station
        climate_dataframes['global'] = df
        climate_station_metadata['global'] = copy.deepcopy(climate_station_metadata[clim_id])

        return climate_dataframes, climate_station_metadata

# =============================================================================
# 5. FILE WRITER CLASS
# Handles all file I/O logic
# =============================================================================
class AnnAGNPSInputWriter:
    """Responsible for writing all output files to disk."""
    def __init__(self, config: AIMSWatershedConfig):
        self.config = config
        self.input_folders: Dict[str, Path] = {}

    def make_watershed_input_dirs(self) -> Dict[str, Path]:
        """Creates the AnnAGNPS directory structure."""
        subdirs = ['general', 'climate', 'simulation', 'watershed']
        if self.config.export_gis:
            subdirs.append('GIS')
        
        folder_paths = annagnps.make_annagnps_inputs_dirs(self.config.output_folder, subdirs=subdirs)
        
        self.input_folders = {dir_name: path for dir_name, path in zip(subdirs, folder_paths)}
        return self.input_folders

    def write_dataframe(self, file_path: Path, df: pd.DataFrame, **kwargs):
        """Generic dataframe writer that respects config.overwrite."""
        if not file_path.exists() or self.config.overwrite:
            if not df.empty:
                df.to_csv(file_path, index=False, **kwargs)

    def write_control_file(self, file_path: Path, data_dict: Dict):
        """Generic control file writer that respects config.overwrite."""
        if not file_path.exists() or self.config.overwrite:
            write_csv_control_file_from_dict(data_dict, output_path=file_path)

    def write_gis_files(self, cells_geometry: gpd.GeoDataFrame, reaches_geometry: gpd.GeoDataFrame):
        """Writes GIS output files."""
        if self.config.export_gis and 'GIS' in self.input_folders:
            gis_dir = self.input_folders['GIS']
            if not (gis_dir / 'cells_geometry.gpkg').exists() or self.config.overwrite:
                cells_geometry.to_file(gis_dir / 'cells_geometry.gpkg', driver='GPKG', index=False)
            if not (gis_dir / 'reaches_geometry.gpkg').exists() or self.config.overwrite:
                reaches_geometry.to_file(gis_dir / 'reaches_geometry.gpkg', driver='GPKG', index=False)

    def write_climate_files(self, climate_dataframes: Dict[str, pd.DataFrame], climate_station_metadata: Dict):
        """Writes all climate_daily and climate_station files."""
        climate_dir = self.input_folders['climate']
        
        for clim_id, df in climate_dataframes.items():
            if clim_id == 'global':
                daily_path = climate_dir / "climate_daily.csv"
                station_path = climate_dir / "climate_station.csv"
            else:
                daily_path = climate_dir / f"climate_daily_{clim_id}.csv"
                station_path = climate_dir / f"climate_station_{clim_id}.csv"

            self.write_dataframe(daily_path, df, float_format="%.3f")
            
            station_meta = climate_station_metadata[clim_id]
            station_meta['output_filepath'] = station_path
            
            if not station_path.exists() or self.config.overwrite:
                climate.generate_climate_station_file(**station_meta)

    def write_master_file(self, master_file_dict: Dict[str, str]):
        """Writes the annagnps_master.csv and AnnAGNPS.fil files."""
        master_path = self.config.output_folder / 'annagnps_master.csv'
        
        # Remove ignored entries
        master_file_dict = {k: v for k, v in master_file_dict.items() if v != 'ignore'}

        df_master = pd.DataFrame({
            'Data Section ID': master_file_dict.keys(),
            'File Name': master_file_dict.values()
        })
        
        self.write_dataframe(master_path, df_master)

        # AnnAGNPS.fil file
        annagnps_fil = self.config.output_folder / 'AnnAGNPS.fil'
        if not annagnps_fil.exists() or self.config.overwrite:
            annagnps_fil.write_text('annagnps_master.csv')

# =============================================================================
# 6. ORCHESTRATOR CLASS
# The main class, now refactored to be a high-level orchestrator
# =============================================================================
class AIMSWatershed:
    def __init__(self, path_to_json_creds: Path, config: AIMSWatershedConfig):
        self.config = config
        self.path_to_json_creds = path_to_json_creds
        
        print(f"Initializing watershed at output folder: {self.config.output_folder}")

        # Setup Database Engine
        credentials = open_creds_dict(path_to_json_creds)
        url_object = create_db_url_object(credentials)
        self.engine = create_engine(url_object, pool_size=30, max_overflow=70, pool_timeout=120, pool_recycle=1800)

        # Initialize components
        self.repository = WatershedRepository(self.engine)
        self.asset_loader = StaticAssetLoader()
        self.climate_processor = ClimateProcessor(self.config, self.repository)
        self.input_writer = AnnAGNPSInputWriter(self.config)

        # Internal state for generated data
        self.bounds: Optional[gpd.GeoDataFrame] = None
        self.master_file_dict: Dict[str, str] = {}
        self.watershed_data_dict: Dict[str, Any] = {}

        # Initial setup
        self._check_outlet_coords()

    def set_metadata(self, config: AIMSWatershedConfig):
        """Replaces the entire configuration object."""
        self.config = config
        # Re-initialize components that depend on config
        self.climate_processor = ClimateProcessor(self.config, self.repository)
        self.input_writer = AnnAGNPSInputWriter(self.config)
        print(f"Configuration updated. Output folder is now: {self.config.output_folder}")

    def _check_outlet_coords(self):
        """Ensures outlet coordinates are set, fetching from DB if needed."""
        if self.config.outlet_x is None or self.config.outlet_y is None:
            if self.config.thuc_id and self.config.reach_id:
                print(f"Fetching outlet x,y from THUC {self.config.thuc_id}, Reach {self.config.reach_id}")
                x, y = self.repository.get_outlet_xy_from_thuc_id_and_reach_id(self.config.thuc_id, self.config.reach_id)
                self.config.outlet_x = x
                self.config.outlet_y = y
            else:
                raise UserWarning("Watershed has no outlet. Set outlet_x/outlet_y or thuc_id/reach_id.")
        
        if self.config.thuc_id is None:
             print(f"Fetching THUC ID from x,y: {self.config.outlet_x}, {self.config.outlet_y}")
             self.config.thuc_id = self.repository.get_thuc_id_by_xy(self.config.outlet_x, self.config.outlet_y)

    # --- Watershed Logic Methods ---
    # These methods perform calculations on dataframes
    
    def get_watershed_bounds(self, cells_geometry: gpd.GeoDataFrame, save: bool = True) -> gpd.GeoDataFrame:
        """Get the watershed outline from the cells geometry."""
        bounds = utils.get_bounds_from_cells(cells_geometry)
        if save:
            self.bounds = bounds
        return bounds
    
    def get_dominant_storm_type(self, scs_storm_types_gdf: gpd.GeoDataFrame, bounds: gpd.GeoDataFrame) -> int:
        """Computes dominant storm type."""
        return annagnps.compute_dominant_storm_type(scs_storm_types_gdf, bounds)
    
    def get_weighted_precip_zones_parameters(self, precip_zones_gdf: gpd.GeoDataFrame, bounds: gpd.GeoDataFrame) -> Tuple[float, float, float]:
        """Computes weighted precip zone parameters."""
        return annagnps.compute_weighted_precip_zones_parameters(precip_zones_gdf, bounds)
    
    def get_watershed_centroid_xy(self, bounds: gpd.GeoDataFrame) -> Tuple[float, float]:
        """Gets the centroid of the watershed bounds."""
        watershed_centroid = bounds.to_crs('epsg:3857').centroid.to_crs('epsg:4326')
        return watershed_centroid.x.to_list()[0], watershed_centroid.y.to_list()[0]

    # --- Main Orchestration Method ---
    
    def generate_annagnps_watershed_input_files(self, perform_data_checks: bool = True):
        """
        Main orchestration method.
        Queries data, processes it, and writes all input files.
        """
        start_time = time.time()
        cfg = self.config # Use a shorthand for config

        # 1. Load static assets
        print('Loading static layers...')
        nldas2_centroids = self.asset_loader.load_nldas2_centroids(cfg.path_to_nldas2_centroids)
        scs_storm_types = self.asset_loader.load_scs_storm_types(cfg.path_to_scs_storm_types)
        precip_zones = self.asset_loader.load_precip_zones(cfg.path_to_precip_zones)

        # 2. Create directory structure
        input_folders = self.input_writer.make_watershed_input_dirs()
        general_dir = input_folders['general']
        watershed_dir = input_folders['watershed']
        simulation_dir = input_folders['simulation']

        # 3. Query main watershed data from repository
        print('Querying watershed data...')
        cells_geometry, df_cells, cells_list = self.repository.query_cells(
            cfg.thuc_id, cfg.outlet_x, cfg.outlet_y, perform_data_checks
        )
        reaches_geometry, df_reaches, reaches_list = self.repository.query_reaches(
            cfg.thuc_id, cfg.outlet_x, cfg.outlet_y
        )

        # 4. Query dependent data
        print('Querying dependent data (Soil & Management)...')
        soil_ids_list = [x for x in df_cells['soil_id'].unique() if not pd.isna(x)]
        df_soil, df_soil_layers, df_raw_soil = self.repository.query_soil(soil_ids_list, perform_data_checks)

        mgmt_field_ids = df_cells['mgmt_field_id'].unique().tolist()
        df_mgmt_field = self.repository.query_management_field(mgmt_field_ids)
        
        mgmt_schedule_ids = df_mgmt_field['Mgmt_Schd_ID'].unique().tolist()
        df_mgmt_schd = self.repository.query_management_schedule(mgmt_schedule_ids)
        
        crop_ids = df_mgmt_schd['New_Crop_ID'].dropna().unique().tolist()
        df_mgmt_crop = self.repository.query_management_crop(crop_ids)
        df_mgmt_crop_growth = self.repository.query_management_crop_growth(crop_ids)
        
        non_crop_ids = df_mgmt_schd['New_Non-Crop_ID'].dropna().unique().tolist()
        df_mgmt_non_crop = self.repository.query_management_non_crop(non_crop_ids)
        
        oper_ids = df_mgmt_schd['Mgmt_Operation_ID'].dropna().unique().tolist()
        df_mgmt_oper = self.repository.query_management_operation(oper_ids)
        
        roc_ids = df_mgmt_schd['Curve_Number_ID'].dropna().unique().tolist()
        df_roc = self.repository.query_runoff_curve(roc_ids)

        # 5. Process Climate Data
        print('Processing climate data...')
        cells_geometry, secondary_climate_ids = self.climate_processor.identify_secondary_climate_ids(
            cells_geometry, nldas2_centroids
        )
        
        # Update df_cells with the new climate IDs
        if 'secondary_climate_file_id' in cells_geometry.columns:
            df_cells = df_cells.set_index('cell_id')
            df_cells.update(cells_geometry.set_index('cell_id')[['secondary_climate_file_id']])
            df_cells = df_cells.reset_index()

        climate_dataframes, climate_station_metadata = self.climate_processor.generate_climate_data(
            cells_geometry, secondary_climate_ids
        )

        # 6. Write Data Files to Disk
        print('Writing data files...')
        self.input_writer.write_gis_files(cells_geometry, reaches_geometry)
        
        self.input_writer.write_dataframe(watershed_dir / 'cell_data_section.csv', df_cells, float_format='%1.5f')
        self.input_writer.write_dataframe(watershed_dir / 'reach_data_section.csv', df_reaches, float_format='%1.5f')
        
        self.input_writer.write_dataframe(general_dir / 'soil_data.csv', df_soil)
        self.input_writer.write_dataframe(general_dir / 'soil_layers_data.csv', df_soil_layers)
        self.input_writer.write_dataframe(general_dir / 'raw_soil_data_gNATSGO.csv', df_raw_soil)
        
        self.input_writer.write_dataframe(general_dir / 'management_oper.csv', df_mgmt_oper)
        df_mgmt_schd_formatted = annagnps.format_mgmt_schedule_for_output(df_mgmt_schd)
        self.input_writer.write_dataframe(general_dir / 'management_schedule.csv', df_mgmt_schd_formatted)
        self.input_writer.write_dataframe(general_dir / 'crop_data.csv', df_mgmt_crop)
        self.input_writer.write_dataframe(general_dir / 'crop_growth.csv', df_mgmt_crop_growth)
        self.input_writer.write_dataframe(general_dir / 'non_crop.csv', df_mgmt_non_crop)
        self.input_writer.write_dataframe(general_dir / 'management_field.csv', df_mgmt_field)
        self.input_writer.write_dataframe(general_dir / 'runoffcurve.csv', df_roc)
        
        self.input_writer.write_climate_files(climate_dataframes, climate_station_metadata)

        # 7. Perform Watershed-Scale Logic
        print('Computing watershed global parameters...')
        bounds = self.get_watershed_bounds(cells_geometry, save=True)
        lon, lat = self.get_watershed_centroid_xy(bounds)
        main_storm_type = self.get_dominant_storm_type(scs_storm_types, bounds)
        r_fctr, ei_10, ei_dom = self.get_weighted_precip_zones_parameters(precip_zones, bounds)

        # 8. Write Control Files
        print('Writing control files...')
        self.watershed_data_dict = {
            'Wshd_Name': cfg.watershed_name,
            'Wshd_Description': cfg.watershed_description,
            'Wshd_Location': cfg.watershed_location,
            'Latitude': lat,
            'Longitude': lon
        }
        self.input_writer.write_control_file(watershed_dir / 'watershed_data.csv', self.watershed_data_dict)
        
        sim_period_data = cfg.simulation_period_data_dict.copy()
        sim_period_data.update({
            'Simulation_Begin_Year': int(cfg.start_date[:4]),
            'Simulation_Begin_Month': int(cfg.start_date[5:7]),
            'Simulation_Begin_Day': int(cfg.start_date[8:10]),
            'Simulation_End_Year': int(cfg.end_date[:4]),
            'Simulation_End_Month': int(cfg.end_date[5:7]),
            'Simulation_End_Day': int(cfg.end_date[8:10]),
            'Rainfall_Fctr': r_fctr,
            '10-Year_EI': ei_10,
            'EI_Number': ei_dom
        })
        self.input_writer.write_control_file(simulation_dir / 'sim_period.csv', sim_period_data)

        globfac_data = cfg.global_factors_flags_dict.copy()
        globfac_data['Wshd_Storm_Type_ID'] = main_storm_type
        self.input_writer.write_control_file(simulation_dir / 'globfac.csv', globfac_data)
        
        self.input_writer.write_control_file(simulation_dir / 'outopts_global.csv', cfg.output_options_global_dict)
        self.input_writer.write_control_file(simulation_dir / 'outopts_aa.csv', cfg.output_options_aa_dict)
        self.input_writer.write_control_file(simulation_dir / 'outopts_tbl.csv', cfg.output_options_tbl_dict)
        self.input_writer.write_control_file(simulation_dir / 'annaid.csv', cfg.annagnps_id_dict)

        df_outopts_rch = pd.DataFrame({'Reach_ID': cfg.selected_reaches_for_output or []})
        self.input_writer.write_dataframe(simulation_dir / 'outopts_rch.csv', df_outopts_rch)

        # 9. Write Master File
        print('Writing master file...')
        master_file = {
            'AnnAGNPS ID': get_relative_path(cfg.output_folder, simulation_dir / 'annaid.csv'),
            'Cell Data': get_relative_path(cfg.output_folder, watershed_dir / 'cell_data_section.csv'),
            'Crop Data': get_relative_path(cfg.output_folder, general_dir / 'crop_data.csv') if not df_mgmt_crop.empty else 'ignore',
            'Crop Growth Data': get_relative_path(cfg.output_folder, general_dir / 'crop_growth.csv') if not df_mgmt_crop_growth.empty else 'ignore',
            'Global IDs Factors and Flags Data': get_relative_path(cfg.output_folder, simulation_dir / 'globfac.csv'),
            'Management Field Data': get_relative_path(cfg.output_folder, general_dir / 'management_field.csv') if not df_mgmt_field.empty else 'ignore',
            'Management Operation Data': get_relative_path(cfg.output_folder, general_dir / 'management_oper.csv') if not df_mgmt_oper.empty else 'ignore',
            'Management Schedule Data': get_relative_path(cfg.output_folder, general_dir / 'management_schedule.csv') if not df_mgmt_schd.empty else 'ignore',
            'Non-Crop Data': get_relative_path(cfg.output_folder, general_dir / 'non_crop.csv') if not df_mgmt_non_crop.empty else 'ignore',
            'Reach Data': get_relative_path(cfg.output_folder, watershed_dir / 'reach_data_section.csv'),
            'Runoff Curve Number Data': get_relative_path(cfg.output_folder, general_dir / 'runoffcurve.csv') if not df_roc.empty else 'ignore',
            'Simulation Period Data': get_relative_path(cfg.output_folder, simulation_dir / 'sim_period.csv'),
            'Soil Data': get_relative_path(cfg.output_folder, general_dir / 'soil_data.csv'),
            'Soil Layer Data': get_relative_path(cfg.output_folder, general_dir / 'soil_layers_data.csv'),
            'Watershed Data': get_relative_path(cfg.output_folder, watershed_dir / 'watershed_data.csv'),
            'Output Options - Global': get_relative_path(cfg.output_folder, simulation_dir / 'outopts_global.csv'),
            'Output Options - AA': get_relative_path(cfg.output_folder, simulation_dir / 'outopts_aa.csv'),
            'Output Options - TBL': get_relative_path(cfg.output_folder, simulation_dir / 'outopts_tbl.csv'),
            'Output Options - Reach': get_relative_path(cfg.output_folder, simulation_dir / 'outopts_rch.csv'),
            'CLIMATE DATA - DAILY': get_relative_path(cfg.output_folder, input_folders['climate'] / 'climate_daily.csv'),
            'CLIMATE DATA - STATION': get_relative_path(cfg.output_folder, input_folders['climate'] / 'climate_station.csv')
        }
        self.master_file_dict = master_file
        self.input_writer.write_master_file(self.master_file_dict)

        end_time = time.time()
        print(f'Finished in {round(end_time - start_time, 2)} seconds')
        print(f'Output folder: {self.config.output_folder}')

    def fragment_watershed(self, **kwargs):
        """
        This function would also be refactored to use the explicit dataframes
        generated in the main method, rather than relying on 'self'.
        """
        # ... implementation from original file ...
        # This method would now need to be updated to
        # use the dataframes generated by the main processing
        # method, rather than reading from 'self.df_cells', etc.
        print("Note: fragment_watershed() needs to be refactored to accept dataframes as arguments.")
        pass

# =============================================================================
# 7. HELPER FUNCTIONS
# =============================================================================
def open_creds_dict(path_to_json_creds: Path) -> Dict:
    """Safely opens and reads a JSON credentials file."""
    with open(path_to_json_creds, "r") as f:
        credentials = json.load(f)
        return credentials
    
def create_db_url_object(credentials: Dict) -> URL:
    """Creates a SQLAlchemy URL object from a credentials dictionary."""
    if isinstance(credentials, (str, Path)):
        credentials = open_creds_dict(Path(credentials))

    return URL.create(
        "postgresql",
        username=credentials["user"],
        password=credentials["password"],
        host=credentials["host"],
        port=credentials["port"],
        database=credentials["database"],
    )

def get_now_string(format="%Y-%m-%d-%H-%M-%S"):
    return datetime.now().strftime(format)

# =============================================================================
# 8. EXAMPLE USAGE
# =============================================================================
if __name__ == "__main__":
    
    print("Running AIMS Watershed Refactored Example...")
    
    # 1. Define the configuration using the new dataclass
    config = AIMSWatershedConfig(
        outlet_x=-90.0,
        outlet_y=34.5,
        start_date="2005-01-01",
        end_date="2005-12-31",
        watershed_name="My Refactored Watershed",
        output_folder=Path("./my_watershed_output"),
        path_to_nldas2_centroids=Path("./gis_static/NLDAS2_GRID_CENTROIDS_epsg4326.gpkg"),
        path_to_scs_storm_types=Path("./gis_static/scs_storm_types.gpkg"),
        path_to_precip_zones=Path("./gis_static/precip_zones_RUSLE2.gpkg"),
        overwrite=True,
        export_gis=True
    )

    # 2. Define path to credentials
    creds_path = Path("path/to/your/db_credentials.json")
    
    if not creds_path.exists():
        print(f"Warning: Credentials file not found at {creds_path}")
        print("Please create it and re-run.")
    else:
        # 3. Initialize the main class
        # This one line now sets up the engine, config, repository,
        # processor, and writer.
        watershed = AIMSWatershed(
            path_to_json_creds=creds_path,
            config=config
        )

        # 4. Run the main orchestration method
        try:
            watershed.generate_annagnps_watershed_input_files(perform_data_checks=True)
            print("Watershed generation complete.")
            
            # 5. Optionally, run fragmentation
            watershed.fragment_watershed(num_processes=8)
            
        except Exception as e:
            print(f"An error occurred during watershed generation: {e}")
            print("This is likely due to placeholder credentials or missing DB connection.")
