# Defining default variables and dictionaries particularly for AnnAGNPS output files

#--- AnnAGNPS Control Files ---

DEFAULT_OUTPUT_OPTIONS_AA = [
    ('Reserved', ''),
    ('Reserved.1', ''),
    ('Reserved.2', ''),
    ('Reserved.3', ''),
    ('Reserved.4', ''),
    ('Reserved.5', ''),
    ('AA_Gullies_Erosion', ''),
    ('Reserved.6', ''),
    ('Reserved.7', ''),
    ('AA_N_Ld_Mass', ''),
    ('AA_N_Ld_Ratio', ''),
    ('AA_N_Ld_UA', ''),
    ('AA_N_Yld_Mass', ''),
    ('AA_N_Yld_Ratio', ''),
    ('AA_N_Yld_UA', ''),
    ('AA_OC_Ld_Mass', ''),
    ('AA_OC_Ld_Ratio', ''),
    ('AA_OC_Ld_UA', ''),
    ('AA_OC_Yld_Mass', ''),
    ('AA_OC_Yld_Ratio', ''),
    ('AA_OC_Yld_UA', ''),
    ('Reserved.8', ''),
    ('Reserved.9', ''),
    ('Reserved.10', ''),
    ('Reserved.11', ''),
    ('Reserved.12', ''),
    ('Reserved.13', ''),
    ('AA_P_Ld_Mass', ''),
    ('AA_P_Ld_Ratio', ''),
    ('AA_P_Ld_UA', ''),
    ('AA_P_Yld_Mass', ''),
    ('AA_P_Yld_Ratio', ''),
    ('AA_P_Yld_UA', ''),
    ('Reserved.14', ''),
    ('Reserved.15', ''),
    ('Reserved.16', ''),
    ('AA_Sed_Eros_Mass', ''),
    ('AA_Sed_Eros_Ratio', ''),
    ('AA_Sed_Eros_UA', 'T'),
    ('AA_Sed_Ld_Mass', ''),
    ('AA_Sed_Ld_Ratio', ''),
    ('AA_Sed_Ld_UA', ''),
    ('AA_Sed_Yld_Mass', ''),
    ('AA_Sed_Yld_Ratio', ''),
    ('AA_Sed_Yld_UA', 'T'),
    ('AA_Wtr_Ld_Mass', ''),
    ('AA_Wtr_Ld_Ratio', ''),
    ('AA_Wtr_Ld_UA', ''),
    ('AA_Wtr_Yld_Mass', ''),
    ('AA_Wtr_Yld_Ratio', ''),
    ('AA_Wtr_Yld_UA', 'T')
]

DEFAULT_OUTPUT_OPTIONS_GLOBAL = [
    ('Glbl_All_V3_csv', ''),
    ('Glbl_All_V3_dpp', ''),
    ('Glbl_All_V3_npt', ''),
    ('Glbl_All_V3_sim', ''),
    ('Glbl_All_V3_txt', ''),
    ('Log_to_File', ''),
    ('Log_to_Screen', ''),
    ('Warning_File', ''),
    ('V1/2_Output_Files', ''),
    ('Reserved', ''),
    ('Glbl_All_Cells', ''),
    ('Glbl_All_Feedlots', ''),
    ('Glbl_All_Fld_Ponds', ''),
    ('Glbl_All_Gullies', ''),
    ('Glbl_All_Pt_Srcs', ''),
    ('Glbl_All_Reaches', ''),
    ('Glbl_All_Impound', ''),
    ('Glbl_All_Wetlands', ''),
    ('Glbl_All_AA_Nutr', ''),
    ('Glbl_All_AA_Pest', ''),
    ('Reserved.1', ''),
    ('Reserved.2', ''),
    ('Glbl_All_AA_Sed', ''),
    ('Glbl_All_AA_Wtr', ''),
    ('Glbl_All_EV_Nutr', 'F'),
    ('Glbl_All_EV_Pest', 'F'),
    ('Glbl_All_EV_Sed', 'T'),
    ('Glbl_All_EV_Wtr', 'T'),
    ('Reserved.3', ''),
    ('Reserved.4', ''),
    ('Glbl_All_V2/3_Mass', ''),
    ('Glbl_All_V2/3_Ratio', ''),
    ('Glbl_All_V2/3_UA', ''),
    ('Reserved.5', ''),
    ('V2_Concepts', 'T'),
    ('Reserved.6', ''),
    ('V2_AA', ''),
    ('V2_EV', ''),
    ('V1_AA', ''),
    ('V1_EV', 'T')
 ]

DEFAULT_OUTPUT_OPTIONS_TBL = [
    ('CCHE1D', 'T'),
    ('CONCEPTS_XML', ''),
    ('Gaging_Station_Hyd', 'F'),
    ('REMM', ''),
    ('Gaging_Station_Evt', '')
]

DEFAULT_ANNAGNPS_ID = [
    ('Version', 6.0),
    ('Input_Units', 1),
    ('Output_Units', 1),
    ('CCHE1D_Output_Units', float('nan')),
    ('Screen_Output_Units', float('nan'))
]